### ISSUE TITLE
[Create] 프로젝트 셋팅

### ISSUE THREAD

**Issue by sujin-kk** [Soptrail/korail-android#1]
## ✏️ Issue
- 프로젝트 기본 셋팅
- style resource 정의

## ✅ ToDo
- [x] 패키지 구조화
- [x] api 셋팅
- [x] binding activity, fragment 초기 작업
- [x] dependency 관리
- [x] drawable 정의
- [x] color 리소스 정의
- [x] string 리소스 정의
- [x] font 리소스 정의
- [x] dimen 리소스 정의
- [x] bottom navigation 구현
- [x] activity, fragment 셋팅
