### ISSUE TITLE
[feat] 3페이지 View 작성

### ISSUE THREAD

**Issue by win-luck** [Soptrail/korail-android#3]
## ✏️ Issue
- 3페이지 xml 파일 구현

## ✅ ToDo
- [x] 리사이클러 뷰 아이템 구현
- [x] 뒤로가기 버튼 구현
- [x] 리사이클러 뷰 fragment와 연결
- [x] LinearLayout ConstraintLayout으로 전부 교체
