### ISSUE TITLE
[Feature] ShowTrainFragment 구현

### ISSUE THREAD

**Issue by win-luck** [Soptrail/korail-android#5]
## ✏️ Issue
- ShowTrainFragment 구현

## ✅ ToDo
- [x] 뒤로가기 버튼 구현
- [x] 스타일 적용
- [x] 3개의 spinner 구현
- [x] 서버통신 성공
- [x] API 결과물 리사이클러뷰에 삽입
- [x] 리사이클러뷰 selection 적용 (선택되었을 때 아이템의 배경색이 엷은 파랑, 가격 버튼의 배경색-파랑, 글자색-흰색이 적용되어야 함.)
- [x] 아이템 매진상태일 때 스타일 변경(전체 글자색 및 일반석 가격버튼 테두리 회색, 특/우등석 가격버튼 버튼스타일 미적용)
- [ ] 아이템 2번 클릭 시 어댑터에서 다른 fragment(승차권 확인)로 이동 (11/23 22:00 기준 미구현 상태 )
